### ISSUE TITLE
Add extra validation to the atlas texture cache (to prevent a potential crash at startup)

### ISSUE THREAD

**Issue by MihanDeNoob** [steves-underwater-paradise/blinkload#11]
full log: https://mclo.gs/E1Y6UlY 
crash log: https://mclo.gs/YQxZUnX

So im the perfect candidate to test this mod, since the very essence of this mod is to improve launch times with modpacks xd
Playing with a huge modpack (570+ mods !!!) that been personally assembled and fine tuned by me. 

Also, my java arguments, have no idea if some of them can cause issues with this mod:
-XX:+UnlockExperimentalVMOptions -XX:+UnlockDiagnosticVMOptions -XX:+AlwaysActAsServerClassMachine -XX:+AlwaysPreTouch -XX:+DisableExplicitGC -XX:AllocatePrefetchStyle=3 -XX:NmethodSweepActivity=1 -XX:ReservedCodeCacheSize=400M -XX:NonNMethodCodeHeapSize=12M -XX:ProfiledCodeHeapSize=194M -XX:NonProfiledCodeHeapSize=194M -XX:-DontCompileHugeMethods -XX:+PerfDisableSharedMem -XX:+UseFastUnorderedTimeStamps -XX:+UseCriticalJavaThreadPriority -XX:+EagerJVMCI -XX:+UseG1GC -XX:MaxGCPauseMillis=37 -XX:+PerfDisableSharedMem -XX:G1HeapRegionSize=16M -XX:G1NewSizePercent=23 -XX:G1ReservePercent=20 -XX:SurvivorRatio=32 -XX:G1MixedGCCountTarget=3 -XX:G1HeapWastePercent=20 -XX:InitiatingHeapOccupancyPercent=10 -XX:G1RSetUpdatingPauseTimePercent=0 -XX:MaxTenuringThreshold=1 -XX:G1SATBBufferEnqueueingThresholdPercent=30 -XX:G1ConcMarkStepDurationMillis=5.0 -XX:GCTimeRatio=99 -XX:G1ConcRefinementServiceIntervalMillis=150 -XX:G1ConcRSHotCardLimit=16 -Xms2G -Xmx6G -XX:+UseLargePages -XX:LargePageSizeInBytes=2m

**Comment by Steveplays28** [comment]
Hi, could you check if your atlas texture cache file is empty (`.minecraft/.blinkload/atlas_texture_cache.json`)?
Either way, try deleting the entire `.minecraft/.blinkload/` folder and relaunching the game. That should fix the issue.

I could add extra validation to the atlas texture cache when I have time.

**Comment by MihanDeNoob** [comment]
I deleted both mod and config folder and installed the mod again xd 
After first launch everything generated correctly, cache.json was not empty but Notepad++ could barely handle it for some reason xd 
Second launch was twice as long then without the mod, i forgot to check cache.json but at least the mod didnt crash at startup. 
Third launch is when it crashed again at start up and when i checked cache.json it was empty.

**Comment by Steveplays28** [comment]
I'll take a look at that issue, that seems new. Thanks for the report!

**Comment by Steveplays28** [comment]
Fixed by #15, released in [`v1.2.0`](https://github.com/steves-underwater-paradise/blinkload/releases/latest).
