### ISSUE TITLE
This mod is cool but there's a weird bug

### ISSUE THREAD

**Issue by CaoTrongThang** [steves-underwater-paradise/blinkload#12]
Everytime i install this mod, and join the game, the "Real Camera" config keep disabling itself

Mods:
accessories-fabric-1.0.0-beta.41+1.20.1.jar
accessories_tclayer-3.8.1-beta.14+1.20.1.jar
AchievementOptimizer-fabric-1.20.1-1.0.1.jar
Ad-Astra-Giselle-Addon-fabric-1.20.1-6.5.jar
advancedgolems-1.20.1-1.5.1-fabric.jar
AdvancementPlaques-1.20.1-fabric-1.6.7.jar
ad_astra-fabric-1.20.1-1.15.19.jar
aetherial-islands-1.0.4.jar
AirHop-v8.0.2-1.20.1-Fabric.jar
almanac-1.20.x-fabric-1.0.2.jar
alternate-current-mc1.20-1.9.0.jar
AmbientSounds_FABRIC_v6.1.3_mc1.20.1.jar
AnvilRepairing-Fabric-1.20.1-4.0.9.jar
Aquamirae-6.jar
architectury-9.2.14-fabric.jar
Armor of the Ages-fabric-1.20.1-1.2.3.jar
artifacts-fabric-9.5.13.jar
athena-fabric-1.20.1-3.1.2.jar
AttributeFix-Fabric-1.20.1-21.0.4.jar
azurelib-fabric-1.20.1-2.0.39.jar
azurelibarmor-fabric-1.20.1-2.0.12.jar
badpackets-fabric-0.4.3.jar
balm-fabric-1.20.1-7.3.9.jar
bclib-3.0.14.jar
better-clouds-1.3.22+1.20.1-fabric.jar
better-end-4.0.11.jar
better-nether-9.0.10.jar
BetterAdvancements-Fabric-1.20.1-0.4.2.10.jar
betterarcheology-1.2.1-1.20.1.jar
bettercampfires-2.3.jar
bettercombat-fabric-1.8.6+1.20.1.jar
BetterGrassify-1.3.4+fabric.1.20.1.jar
betterpickaxetrims-fabric-1.20.1-1.0.0.jar
BetterTridents-v8.0.1-1.20.1-Fabric.jar
birdnest-fabric-1.1.1+mc1.20.1.jar
BOMD-1.7.5-1.20.1.jar
Bookshelf-Fabric-1.20.1-20.2.13.jar
botarium-fabric-1.20.1-2.3.4.jar
Bountiful-6.0.4+1.20.1-fabric.jar
BridgingMod-2.5.1+1.20.1.fabric-release.jar
c2me-fabric-mc1.20.1-0.2.0+alpha.11.13.jar
cardinal-components-api-5.2.2.jar
carryon-fabric-1.20.1-2.1.2.7.jar
chat_heads-0.13.7-fabric-1.20.jar
cherishedworlds-fabric-6.1.6+1.20.1.jar
chipped-fabric-1.20.1-3.0.7.jar
chunksfadein-1.0.7-1.20.1.jar
cloth-config-11.1.136-fabric.jar
Clumps-fabric-1.20.1-12.0.0.4.jar
collective-1.20.1-7.87.jar
combatroll-fabric-1.3.3+1.20.1.jar
common-networking-fabric-1.0.5-1.20.1.jar
Configurable-2.2.0-fabric-yarn+1.20.1.jar
Controlling-fabric-1.20.1-12.0.2.jar
coroutil-fabric-1.20.1-1.3.7.jar
craftingtweaks-fabric-1.20.1-18.2.5.jar
CreativeCore_FABRIC_v2.12.22_mc1.20.1.jar
creeper-healing-1.0.0-1.20.jar
creeperoverhaul-3.0.2-fabric.jar
Croptopia-1.20.1-FABRIC-3.0.4.jar
cupboard-fabric-1.20.1-2.7.jar
custom-item-despawn-duration-fabric-0.1.0-1.20.1.jar
damagenumbers-1.4.0-fabric.jar
dark-loading-screen-1.6.14.jar
dark-waters-1.20.1-0.0.22.jar
Debugify-1.20.1+2.0.jar
deeperdarker-fabric-1.20-1.3.2.1.jar
dehydration-1.3.6.jar
doubledoors-1.20.1-5.9.jar
Dungeon Now Loading-fabric-1.20.1-1.5.jar
DungeonsArise-1.20.1-2.1.57-fabric-release.jar
DungeonsAriseSevenSeas-1.20.x-1.0.2-fabric.jar
e4mc_minecraft-fabric-5.2.1.jar
EasyAnvils-v8.0.2-1.20.1-Fabric.jar
EasyMagic-v8.0.1-1.20.1-Fabric.jar
eating-animation-1.20+1.9.61.jar
eden-ring-20.1.20.jar
edf-remastered-4.3.jar
efallingtrees-0.6.0-1.20+fabric.jar
effective-2.3.2-1.20.1.jar
elytraslot-fabric-6.4.4+1.20.1.jar
EnchantmentDescriptions-Fabric-1.20.1-17.1.19.jar
endermanoverhaul-fabric-1.20.1-1.0.4.jar
enhancedblockentities-0.9+1.20.jar
EnhancedVisuals_FABRIC_v1.8.1_mc1.20.1.jar
entityculling-fabric-1.7.1-mc1.20.1.jar
entity_model_features_fabric_1.20.1-2.2.6.jar
entity_texture_features_fabric_1.20.1-6.2.8.jar
EpheroLib-1.20.1-FABRIC-1.2.0.jar
Epic Dungeons-0.1.04-Fabric-1.19-1.20.4.jar
expandeddelight-0.3.2.jar
ExplorersCompass-1.20.1-2.2.3-fabric.jar
explosive-enhancement-1.2.2-1.20.x.jar
fabric-api-0.92.2+1.20.1.jar
fabric-language-kotlin-1.12.3+kotlin.2.0.21.jar
fabric-seasons-2.4.2-BETA+1.20.jar
fabric-seasons-croptopia-2.2.2-compat-1.0.jar
fabric-seasons-delight-1.3.9-compat-1.0.jar
fabric-seasons-extras-1.3.2-BETA+1.20.jar
fabric-seasons-terralith-2.3.7-compat-1.0.jar
fabricskyboxes-0.7.3+mc1.20.1.jar
fakerlib-0.1.4.jar
fallingleaves-1.15.6+1.20.1.jar
fancymenu_fabric_3.3.2_MC_1.20.1.jar
fantasy_armor-fabric-0.5-1.20.1.jar
fantasy_weapons-fabric-0.2-1.20.1.jar
FarmersDelight-1.20.1-2.2.0+refabricated.jar
farmersknives-3.2.jar
farmingforblockheads-fabric-1.20.1-14.0.2.jar
fasterrandom-5.1.0.jar
ferritecore-6.0.1-fabric.jar
Fishingreal-1.20.1-1.7.2.jar
fixedanvilrepaircost-1.20.1-3.4.jar
flowermimics-1.20.1-2.0.jar
foodeffecttooltips-1.1.1-1.20.0.jar
ForgeConfigAPIPort-v8.0.1-1.20.1-Fabric.jar
friendsandfoes-fabric-mc1.20.1-3.0.6.jar
fzzy_config-0.5.8+1.20.1.jar
fzzy_core-0.5.1+1.20.1.jar
GameDiscs-0.3.1-fabric.jar
gazebo-1.1.1+1.20.1.jar
gear_core-0.3.8+1.20.1.jar
geckolib-fabric-1.20.1-4.4.9.jar
GhastCow-fabric-1.20.1-2.0.0.jar
giantspawn-1.20.1-5.2.jar
gliders-fabric-1.1.6.jar
gravestones-1.0.9-1.20.1.jar
guardvillagers-2.0.9-1.20.1.jar
hardcore_torches_fabric-1.20.1-1.6.5.jar
held-item-info-1.5.0.jar
hostilevillages-fabric-1.20.1-5.7.jar
Icarae-Origin-Fabric-1.1.0-alpha.2.jar
Icarus-Fabric-2.10.0.jar
iceandfire-0.7.1.jar
Iceberg-1.20.1-fabric-1.1.25.jar
IllagerInvasion-v8.0.6-1.20.1-Fabric.jar
ImmediatelyFast-Fabric-1.3.2+1.20.4.jar
immersivelanterns-fabric-1.0.5-1.20.1.jar
ImmersiveUI-FABRIC-0.2.2.jar
immersive_aircraft-1.1.5+1.20.1-fabric.jar
immersive_armors-1.6.1+1.20.1-fabric.jar
immersive_melodies-0.3.0+1.20.1-fabric.jar
improvedmobs-1.20.1-1.13.0-fabric.jar
indium-1.0.34+mc1.20.1.jar
inventory-weight-1.3.4_1.20-1.20.4.jar
inventoryessentials-fabric-1.20.1-8.2.6.jar
inventoryhud.fabric.1.20.1-3.4.26.jar
InventoryProfilesNext-fabric-1.20-1.10.11.jar
iris-1.7.5+mc1.20.1.jar
ItemBorders-1.20.1-fabric-1.2.2.jar
Jadens-Nether-Expansion-2.1.3-Fabric.jar
jamlib-0.6.1+1.20.x.jar
jumpanimation-1.0.0-fabric-1.20.1.jar
Jupiter-2.0-fabric.jar
Kambrik-6.1.1+1.20.1-fabric.jar
keybind_fix-1.0.0.jar
knightlib-fabric-1.20.1-1.1.0.jar
knightquest-fabric-1.20.1-1.7.2.jar
konkrete_fabric_1.8.1_MC_1.20.1.jar
krypton-0.2.3.jar
language-reload-1.7.1+1.20.1.jar
lavender-0.1.9+1.20.jar
leawind_third_person-v2.2.0-beta.4-mc1.20-1.20.1-fabric.jar
LegendaryTooltips-1.20.1-fabric-1.4.5.jar
letmedespawn-1.20.x-fabric-1.4.4.jar
Lexiconfig-fabric-1.3.11.jar
libIPN-fabric-1.20-4.0.2.jar
lithium-fabric-mc1.20.1-0.11.2.jar
loadingbackgrounds-fabric-1.20.2-1.5.0.jar
Log-Begone-Fabric-1.20.1-1.0.8.jar
logcleaner-1.0.0.jar
lukis-grand-capitals-1.1.1.jar
majrusz-library-fabric-1.20.1-7.0.8.jar
majruszs-difficulty-fabric-1.20.1-1.9.10.jar
mcda-5.0.2.jar
mcdar-4.0.4.jar
mcde-1.6.4-1.20.jar
mcdw-9.0.4.jar
mebahel-zombie-horde-1.0.7-1.20.1.jar
melody_fabric_1.0.4_MC_1.20.1-1.20.4.jar
memoryleakfix-fabric-1.17+-1.1.5.jar
midnightlib-fabric-1.4.1.1.jar
minecells-1.9.1.jar
mixintrace-1.1.1+1.17.jar
MobCaptains-v3.1.2.jar
modelfix-1.15-fabric.jar
modernfix-fabric-5.19.5+mc1.20.1.jar
modmenu-7.2.2.jar
moonlight-1.20-2.13.32-fabric.jar
moreculling-1.20.4-0.24.0.jar
MRU-1.0.4+1.20.1+fabric.jar
My Totem Doll-1.0.1+1.20.1.jar
mysticaloaktree-1.20-1.11-fabric.jar
NaturesCompass-1.20.1-2.2.3-fabric.jar
neutral-animals-1.2.4.jar
nevermore-0.1.0.jar
noisium-fabric-2.3.0+mc1.20-1.20.1.jar
notenoughanimations-fabric-1.8.1-mc1.20.1.jar
Obscure-API-16.jar
oceansdelight-fdrf-fabric-1.0.2-1.20.jar
OctoLib-FABRIC-0.4.2+1.20.1.jar
Origins-1.20.1-1.10.0.jar
owo-lib-0.11.2+1.20.jar
packetfixer-fabric-1.4.2-1.19-to-1.20.1.jar
particle_core-0.2.5+1.20.1.jar
Patchouli-1.20.1-84-FABRIC.jar
Paxi-1.20-Fabric-4.0.jar
physics-mod-3.0.14-mc-1.20.1-fabric.jar
PickUpNotifier-v8.0.0-1.20.1-Fabric.jar
Ping-Wheel-1.10.0-fabric-1.20.1.jar
player-animation-lib-fabric-1.0.2-rc1+1.20.jar
pneumonocore-1.1.4+1.20.1.jar
pocketgps-fabric-1.20.1-1.0.6.jar
polymorph-fabric-0.49.7+1.20.1.jar
PresenceFootsteps-1.10.1+1.20.1.jar
Prism-1.20.1-fabric-1.0.5.jar
PuzzlesLib-v8.1.25-1.20.1-Fabric.jar
pyrofrost-1.0.1.jar
radiantgear-fabric-2.1.6+1.20.1.jar
ranged_weapon_api-1.1.4+1.20.1.jar
realcamera-1.20.1-fabric-0.6.1-beta.jar
reeses_sodium_options-1.7.2+mc1.20.1-build.101.jar
remove-terralith-intro-message-1.1.jar
resourcefulconfig-fabric-1.20.1-2.1.2.jar
resourcefullib-fabric-1.20.1-2.1.29.jar
Ribbits-1.20.1-Fabric-3.0.0.jar
right-click-harvest-3.2.3+1.19.x-1.20.1-fabric.jar
RingsOfAscension-1.20.1-2.0.2.jar
rocks-1.7.1.jar
roughly-searchable-2.6.0+1.20.1.jar
RoughlyEnoughItems-12.1.785-fabric.jar
RoughlyEnoughProfessions-fabric-1.20.1-2.0.2.jar
rrls-4.0.6.1+mc1.20.1-fabric.jar
runes-0.9.13+1.20.1.jar
sawmill-1.20-1.4.3-fabric.jar
scorched-1.1.3e.jar
Searchables-fabric-1.20.1-1.0.3.jar
shulkerboxtooltip-fabric-4.0.4+1.20.1.jar
simplyswords-fabric-1.56.0-1.20.1.jar
sit!-1.1.10+1.20.1.jar
SkyVillages-1.0.4-1.19.2-1.20.1-fabric.jar
sleepy_hollows-fabric-1.0.2.jar
smallships-fabric-1.20.1-2.0.0-b1.4.jar
SmartBrainLib-fabric-1.20.1-1.15.jar
smarterfarmers-1.20-2.1.0-fabric.jar
smoothscroll-2.1.3.1+1.20.1.jar
sodium-extra-0.5.4+mc1.20.1-build.115.jar
sodium-fabric-0.5.11+mc1.20.1.jar
sodiumdynamiclights-fabric-1.0.9-1.20.1.jar
sodiumoptionsapi-fabric-1.0.8-1.20.1.jar
soulslike-weaponry-1.1.5-1.20.1-fabric.jar
Sounds-2.2.0+1.20.1+fabric.jar
spark-1.10.53-fabric.jar
sparkle-1.1.0.jar
sparsestructures-fabric-1.20.1-2.2.0.jar
spawnersplus-4.0-1.20.1.jar
spell_engine-0.15.11+1.20.1.jar
spell_power-0.12.0+1.20.1.jar
starlight-1.1.2+fabric.dbc156f.jar
structure_pool_api-1.0+1.20.1.jar
supermartijn642configlib-1.1.8a-fabric-mc1.20.jar
supermartijn642corelib-1.1.17a-fabric-mc1.20.1.jar
swingthrough-1.0.6+1.20.jar
tectonic-fabric-1.20.1-2.4.1b.jar
tenshilib-1.20.1-1.7.6-fabric.jar
TerraBlender-fabric-1.20.1-3.0.1.7.jar
Terralith_1.20.x_v2.5.4.jar
The_Graveyard_3.1_(FABRIC)_for_1.20.1.jar
things-0.3.3+1.20.jar
threadtweak-fabric-1.20.2-0.1.1.jar
tia-1.20-1.1-fabric.jar
Tips-Fabric-1.20.1-12.1.8.jar
toms_storage_fabric-1.20-1.6.8.jar
TooManyOrigins-1.1.4+1.20.1-fabric.jar
trashcans-1.0.18-fabric-mc1.20.jar
travelersbackpack-fabric-1.20.1-9.1.18.jar
twilightforest-fabric-1.20.1-1.4.2.jar
txnilib-fabric-1.0.19-1.20.1.jar
Uranus-1.7.1.jar
visuality-0.7.1+1.20.jar
walk-jog-run-1.1.0+1.20.1.jar
wardentools-2.5.0+mc1.20.1.jar
weaponleveling-1.20.1-2.2.2-fabric.jar
weapons_expanded_1.20.1_1.5.3_fabric.jar
welcometomyworld-2.4.jar
wetlands-1.2-1.20.1.jar
wildlife-1.20.1-2.2.jar
wraith-waystones-3.3.2+mc1.20.1.jar
wthit-fabric-8.15.3.jar
Xaeros_Minimap_24.6.1_Fabric_1.20.jar
YetAnotherConfigLib-3.6.1+1.20.1-fabric.jar
YouDied-1.20-3.0.0.17-fabric.jar
YungsApi-1.20-Fabric-4.0.6.jar
YungsBetterDesertTemples-1.20-Fabric-3.0.3.jar
YungsBetterDungeons-1.20-Fabric-4.0.4.jar
YungsBetterEndIsland-1.20-Fabric-2.0.6.jar
YungsBetterJungleTemples-1.20-Fabric-2.0.5.jar
YungsBetterMineshafts-1.20-Fabric-4.0.4.jar
YungsBetterNetherFortresses-1.20-Fabric-2.0.6.jar
YungsBetterOceanMonuments-1.20-Fabric-3.0.4.jar
YungsBetterStrongholds-1.20-Fabric-4.0.3.jar
YungsBetterWitchHuts-1.20-Fabric-3.0.3.jar
YungsBridges-1.20-Fabric-4.0.3.jar
YungsCaveBiomes-1.20.1-Fabric-2.0.0.jar

**Comment by Steveplays28** [comment]
Thanks for the report!

**Comment by Steveplays28** [comment]
Fixed by #15, released in [`v1.2.0`](https://github.com/steves-underwater-paradise/blinkload/releases/latest).
