### ISSUE TITLE
Crashes not sure why.

### ISSUE THREAD

**Issue by sherpascott** [steves-underwater-paradise/blinkload#13]
[crash-2024-12-01_05.42.55-client.txt](https://github.com/user-attachments/files/17968933/crash-2024-12-01_05.42.55-client.txt)

This is the crash report it gives me. Happens only on the second or third loading attempt, but not at first (like it has no problem creating the cache just loading it) I'm using this modpack: https://www.curseforge.com/minecraft/modpacks/reimagined-forge

Forge 1.20.1 latest version

Thanks in advance for helping! Let me know if I can provide any more information.

**Comment by Steveplays28** [comment]
Fixed by #15, released in [`v1.2.0`](https://github.com/steves-underwater-paradise/blinkload/releases/latest). Thank you for the report.
