### ISSUE TITLE
textures bug out and become seethrough

### ISSUE THREAD

**Issue by KingOfStrangeness69** [steves-underwater-paradise/blinkload#6]
![image](https://github.com/user-attachments/assets/ca914487-df09-4164-802f-82188b1b1965)
basically what the title says

**Comment by Steveplays28** [comment]
Duplicate of #5. Sorry about this issue, I've not yet found out why it happens.

**Comment by Steveplays28** [comment]
Fixed in [`v1.1.0`](https://github.com/steves-underwater-paradise/blinkload/releases/latest).
